bwa=/share/tools-Juantxo/bwa-0.7.17/bwa
genome=/share/tools-Juantxo/genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa
CIRIDIR=/share/tools-Juantxo/circRNA/CIRI-full_v2.0
OUTPUTDIR=/share/analysis/hecatos/juantxo/circRNA/ciri2/${tissue}/${compound}
CIRI2=$CIRIDIR/bin/CIRI_v2.0.6/CIRI2.pl
CIRIASV1=$CIRIDIR/bin/CIRI_AS_v1.2/CIRI_AS_v1.2.pl
indexgenome="false" # First time, true.
GTFFTP=ftp://ftp.ensembl.org/pub/release-92/gtf/homo_sapiens/Homo_sapiens.GRCh38.92.gtf.gz
GTF=/share/analysis/hecatos/juantxo/circRNA/ciri2/Homo_sapiens.GRCh38.92.gtf
# compound="con_DF2"
compoundfolder=""
# timeCTRL=("000" "002" "008" "024" "072" "168" "240" "336")
#dose=("The")
samplename=()
reads=("R1" "R2")
# replicates=("1" "2" "3")

mkdir $OUTPUTDIR
cd $OUTPUTDIR
wget $GTFFTP
gunzip ${GTF}.gz

#for d in ${dose[@]}; do
#  if [ "$d"  ==  "Tox" ]; then
#    time=${timeTOX[@]}
#  else
#    time=${timeTHE[@]}
#  fi
  for t in ${timeCTRL[@]}; do
    for r in ${replicates[@]}; do
      samplename+=("${compound}_${t}_${r}");
    done;
  done;
#done;

for rep in ${samplename[@]} ; do
  # FQR1=/ngs-data/data/hecatos/${tissue}/${compid}/TotalRNA/${trimmed_dir}/${rep}_R1_2_trimmed.fastq
  # FQR2=/ngs-data/data/hecatos/${tissue}/${compid}/TotalRNA/${trimmed_dir}/${rep}_R2_2_trimmed.fastq
  prefix="df2-pe-trimmed-${rep}"

  # gunzip ${FQR1}.gz
  # gunzip ${FQR2}.gz

  # rm -r ${prefix}_output
  mkdir ${prefix}_output

  if $indexgenome; then
    $bwa index $genome
  fi
  # $bwa mem -T 19 -t 12 $genome $FQR1 $FQR2 > ${prefix}_output/${prefix}.sam
  if [ "$(stat --printf="%s" ${prefix}_output/${prefix}.sam)" = 0 ] ; then
    echo "bwa mem failed"
    exit 1
  fi
  perl $CIRI2 -I ${prefix}_output/${prefix}.sam -O ${prefix}_output/${prefix}.ciri -F $genome -A $GTF
  if [ "$(stat --printf="%s" ${prefix}_output/${prefix}.ciri)" = 0 ] ; then
    echo "ciri2 failed"
    exit 1
  fi
  perl $CIRIASV1 -S ${prefix}_output/${prefix}.sam -C ${prefix}_output/${prefix}.ciri -F $genome -A $GTF -O ${prefix}_output/${prefix} -D yes
  # java -jar ${CIRIDIR}/CIRI-full.jar RO1 -1 $FQR1 -2 $FQR2 -o ${prefix}_output/${prefix}
  # $bwa mem -T 19 $genome ${prefix}_output/${prefix}_ro1.fq > ${prefix}_output/${prefix}_ro1.sam
  # java -jar ${CIRIDIR}/CIRI-full.jar RO2 -r $genome -s ${prefix}_output/${prefix}_ro1.sam -l 100 -o ${prefix}_output/${prefix}
  # java -jar ${CIRIDIR}/CIRI-full.jar Merge -c ${prefix}_output/${prefix}.ciri -as ${prefix}_output/${prefix}_jav.list -ro ${prefix}_output/${prefix}_ro2_info.list -a $GTF -r $genome -o ${prefix}_output/${prefix}
  unset DISPLAY
  # java -jar ${CIRIDIR}/CIRI-vis.jar -i ${prefix}_output/${prefix}_merge_circRNA_detail.anno -l ${prefix}_output/${prefix}_library_length.list -r $genome -min 1

    # gzip ${FQR1}
    # gzip ${FQR2}




done

#rm $GTF

# Combine AS and RO output
# Exception in thread "main" java.lang.reflect.InvocationTargetException
# Caused by: java.lang.NumberFormatException: For input string: "n/a"

# Remember not to run 2 scripts in the same output folder (especially when it starts by removing everything that was previously there)

# No circRNA list found at designated directory!
# Please make sure the SAM is the same one used for circRNA detection by CIRI without modification!
# Please make sure the SAM was generated by BWA-MEM using PE mode and was not modified!
